markdown: rdiscount
pygments: true
plugins: ./_plugins
paginate: 8

exclude: ['_samples/']

safe: false

#站点基础配置
title: Panorama
subTitle: ssfhljy's personal blog site.
description: This is a personal blog site based on Jekyll and originated from PIZn's GUI design.
url: https://ssfhljy.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: Home
    url: /index.html
    icon: icon-home
    class: home
  - text: Archives
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: Tags
    url: /tags.html
    icon: icon-flag
    class: none
  - text: Projects
    url: /projects.html
    icon: icon-github
    class: none
  - text: Links
    url: /links.html
    icon: icon-heart
    class: none
  - text: About
    url: /about.html
    icon: icon-envelope-alt
    class: none
  - text: Search
    url: /search.html
    icon: icon-search
    class: none
page:
  - text: Archives
    url: /archives.html
    last: true
  - text: Links
    url: /links.html
    last: true
  - text: About
    url: /about.html
    last: true
  - text: Tags
    url: /tags.html
    last: false
author:
  name: ssfhljy
