markdown: rdiscount
pygments: true
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: iLotus
subTitle: Just another Jekyll blog.
description: 这是 PIZn 的又一个博客，它是基于 Jekyll 搭建起来的。在这里，不仅仅是用来快速记录工作，学习，生活的一点一滴的地方，更是 PIZn 对 Jekyll 的学习和使用的一次有意义的实践。
url: https://ssfhljy.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: Home
    url: /index.html
    icon: icon-home
    class: home
  - text: Archives
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: Tags
    url: /tags.html
    icon: icon-flag
    class: none
  - text: Projects
    url: https://github.com/ssfhljy
    icon: icon-github
    class: none
  - text: Links
    url: /links.html
    icon: icon-heart
    class: none
  - text: About
    url: /about.html
    icon: icon-envelope-alt
    class: none
page:
  - text: Archives
    url: /archives.html
    last: true
  - text: Links
    url: /links.html
    last: true
  - text: About
    url: /about.html
    last: true
  - text: Tags
    url: /tags.html
    last: false
author:
  name: PIZn
