auto: true

markdown: kramdown #rdiscount
pygments: true
paginate: 8
permalink: /:title
exclude: ['README.md']

title: Panorama
url: http://ssfhljy.github.io
feed: /atom.xml
author_info: <a href="http://ssfhljy.github.io/">ssfhljy</a>
